'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace LeaderboardPage


    Partial Public Class Leaderboard


        ''' <summary>
        ''' form1 control.
        ''' </summary>

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm


        ''' <summary>
        ''' pnlError control.
        ''' </summary>

        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel


        ''' <summary>
        ''' pnlEmpty control.
        ''' </summary>

        Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel


        ''' <summary>
        ''' rptLeaderboard control.
        ''' </summary>

        Protected WithEvents rptLeaderboard As Global.System.Web.UI.WebControls.Repeater

        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

    End Class

End Namespace