'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Class Account_Login

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

    Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label

    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

End Class