'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ChallengePage

    Partial Public Class Challenge

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' lblUsername control.
        ''' </summary>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        ''' <summary>
        ''' lblLevel control.
        ''' </summary>
        Protected WithEvents lblLevel As Global.System.Web.UI.WebControls.Label

        ''' <summary>
        ''' litCollectedCodes control.
        ''' </summary>
        Protected WithEvents litCollectedCodes As Global.System.Web.UI.WebControls.Literal

        ''' <summary>
        ''' litProblem control.
        ''' </summary>
        Protected WithEvents litProblem As Global.System.Web.UI.WebControls.Literal

        ''' <summary>
        ''' litExpectedOutput control.
        ''' </summary>
        Protected WithEvents litExpectedOutput As Global.System.Web.UI.WebControls.Literal

        ''' <summary>
        ''' hiddenLevel control.
        ''' </summary>
        Protected WithEvents hiddenLevel As Global.System.Web.UI.WebControls.HiddenField

        ''' <summary>
        ''' hiddenUsername control.
        ''' </summary>
        Protected WithEvents hiddenUsername As Global.System.Web.UI.WebControls.HiddenField

        ''' <summary>
        ''' hiddenUserId control.
        ''' </summary>
        Protected WithEvents hiddenUserId As Global.System.Web.UI.WebControls.HiddenField

    End Class

End Namespace