'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ProfilePage

    Partial Public Class Profile

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblHeaderUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHeaderLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderLevel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblGlobalRank control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGlobalRank As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentXP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentXP As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divXpFill control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divXpFill As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblStatTotalScore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatTotalScore As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStatGamesPlayed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatGamesPlayed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStatWins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatWins As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStatWinRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatWinRate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptRecentGames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptRecentGames As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblInfoName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfoName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInfoID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfoID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInfoLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfoLevel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInfoHighScore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfoHighScore As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInfoGamesLost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfoGamesLost As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBestLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBestLevel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPerfHighScore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPerfHighScore As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBestStreak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBestStreak As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCodesCollected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCodesCollected As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBugsAvoided control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBugsAvoided As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace